#!/usr/bin/env python3

import sys
import struct

def make_header(file_count):
  data = bytearray()
  data += b"CRAW"
  data += struct.pack("<I", file_count)
  data += bytes(512 - len(data))
  return data

def main():
  if len(sys.argv) == 2:
    try: _ = int(sys.argv[1])
    except:
      print("Usage: ./boot <file_count> <output.bin>")
      sys.exit(1)
    finally: output = "boot.bin"

  else: output = sys.argv[2]

  if len(sys.argv) not in (2, 3):
    print("Usage: ./boot <file_count> <output.bin>")
    sys.exit(1)

  file_count = int(sys.argv[1])

  data = make_header(file_count)

  with open(output, "wb") as f: f.write(data)

  print(f"Wrote {output}")
  print(f"File count: {file_count}")

if __name__ == "__main__": main()
