import re
from imm import i as construct
from song_parser import NOTE_FREQS
from speech_parser import PHONEMES, WAVE as SPEECH_WAVE

OUTPUT_FILE = "performance.craw"

MUSIC_CHANNELS = 4
SPEECH_CHANNELS = 4

MUSIC_OFFSET = 0
SPEECH_OFFSET = 4

TOTAL_TICK_MS = 1000
BREAK_MS = 30
MUSIC_ON_MS = TOTAL_TICK_MS - BREAK_MS

MUSIC_VOLUME = 45
MUSIC_WAVE = 0

NOTE_RE = re.compile(r"^[A-G](#|b)?[0-8]\*?$")


def insert_large(value, out):
  if -128 <= value <= 127:
    out.append(f"sav {value} r01")
    return out

  out.append("sav 7 r02")
  blocks = construct(value, 0, False)

  for i, block in enumerate(blocks):
    if i + 1 == len(blocks):
      out.append(f"cal add {block} r01")
    else:
      out.extend([
        f"sav {block} r01",
        "cal shl r01 r02",
      ])

  return out


def emit_channel(out, channel):
  out.extend([
    f"sav {channel} r01",
    "io speaker channel r01",
  ])


def emit_freq(out, freq):
  insert_large(freq, out)
  out.append("io speaker freq r01")


def emit_volume(out, volume):
  out.extend([
    f"sav {volume} r01",
    "io speaker volume r01",
  ])


def emit_wave(out, wave):
  out.extend([
    f"sav {wave} r01",
    "io speaker wave r01",
  ])

def emit_on(out):
  out.append("io speaker on rff")

def emit_off(out):
  out.append("io speaker off rff")

def emit_letters(out, chars):
  for c in chars: out.append(f"sav {ord(c)} ref")

def emit_sleep(out, ms):
  if ms <= 0:
    return
  insert_large(ms, out)
  out.append("io time sleep r01")


def emit_stop_range(out, start, count):
  for channel in range(start, start + count):
    emit_channel(out, channel)
    emit_off(out)


def parse_song_tick(raw_line, line_number):
  line = raw_line.split(";")[0].strip()

  if line == "" or line == "-":
    return []

  parsed = []

  for token in line.split():
    if not NOTE_RE.match(token):
      raise Exception(f"Bad note token '{token}' on song line {line_number}")

    hold = token.endswith("*")
    note = token[:-1] if hold else token

    if note not in NOTE_FREQS:
      raise Exception(f"Unknown note '{note}' on song line {line_number}")

    parsed.append((note, hold))

  notes = [note for note, _ in parsed]

  if len(notes) != len(set(notes)):
    raise Exception(f"Duplicate note on song line {line_number}")

  if len(parsed) > MUSIC_CHANNELS:
    raise Exception(f"Too many music notes on song line {line_number}")

  return parsed


def parse_speech_tick(raw_line, line_number):
  line = raw_line.split(";")[0].strip().upper()

  if line == "" or line == "-":
    return []

  tokens = line.split()

  for token in tokens:
    if token not in PHONEMES:
      raise Exception(f"Unknown phoneme '{token}' on speech line {line_number}")

  return tokens


def free_music_channel(active):
  for channel in range(MUSIC_CHANNELS):
    if active[channel] is None:
      return channel

  return None


def emit_music_setup(out):
  out.extend([
    "; music setup",
    f"sav {MUSIC_VOLUME} r02",
    f"sav {MUSIC_WAVE} r03",
    "",
  ])

  for channel in range(MUSIC_CHANNELS):
    emit_channel(out, MUSIC_OFFSET + channel)
    out.extend([
      "io speaker volume r02",
      "io speaker wave r03",
      "io speaker off rff",
      "",
    ])


def emit_speech_setup(out):
  out.extend([
    "; speech setup",
    "",
  ])

  for channel in range(SPEECH_CHANNELS):
    emit_channel(out, SPEECH_OFFSET + channel)
    emit_wave(out, SPEECH_WAVE)
    emit_volume(out, 0)
    emit_off(out)
    out.append("")


def emit_speech_channels(out, channels):
  emit_stop_range(out, SPEECH_OFFSET, SPEECH_CHANNELS)

  for channel, freq, volume in channels:
    emit_channel(out, SPEECH_OFFSET + channel)
    emit_freq(out, freq)
    emit_volume(out, volume)
    emit_on(out)


def emit_speech_phoneme(out, name):
  phoneme = PHONEMES[name]
  elapsed = 0

  out.append(f"; speech phoneme {name}")

  emit_letters(out, name)

  if "steps" in phoneme:
    step_duration = phoneme["duration"] // len(phoneme["steps"])

    for step in phoneme["steps"]:
      emit_speech_channels(out, step)
      emit_sleep(out, step_duration)
      elapsed += step_duration

    emit_stop_range(out, SPEECH_OFFSET, SPEECH_CHANNELS)
    emit_sleep(out, 10)
    elapsed += 10

    return elapsed

  emit_speech_channels(out, phoneme["channels"])
  emit_sleep(out, phoneme["duration"])
  elapsed += phoneme["duration"]

  emit_stop_range(out, SPEECH_OFFSET, SPEECH_CHANNELS)
  emit_sleep(out, 10)
  elapsed += 10

  return elapsed

def compile_performance(song_lines, speech_lines):
  out = [
    "; Generated by performance.py (C) CRAW SYSTEMS",
    "",
  ]

  emit_music_setup(out)
  emit_speech_setup(out)

  active_music = {channel: None for channel in range(MUSIC_CHANNELS)}
  total_ticks = max(len(song_lines), len(speech_lines))

  for tick_index in range(total_ticks):
    song_raw = song_lines[tick_index] if tick_index < len(song_lines) else "-"
    speech_raw = speech_lines[tick_index] if tick_index < len(speech_lines) else "-"

    song_tick = parse_song_tick(song_raw, tick_index + 1)
    speech_tick = parse_speech_tick(speech_raw, tick_index + 1)

    tick_notes = {note for note, _ in song_tick}
    instant_notes = {note for note, hold in song_tick if not hold}

    out.append(f"; ===== tick {tick_index + 1} =====")
    out.append(f"; song: {song_raw.strip()}")
    out.append(f"; speech: {speech_raw.strip()}")

    for channel, note in list(active_music.items()):
      if note is not None and note not in tick_notes:
        emit_channel(out, MUSIC_OFFSET + channel)
        emit_off(out)
        active_music[channel] = None

    already_active = {
      note: channel
      for channel, note in active_music.items()
      if note is not None
    }

    tick_channel_for_note = {}

    for note, hold in song_tick:
      if note in already_active:
        tick_channel_for_note[note] = already_active[note]
        continue

      channel = free_music_channel(active_music)

      if channel is None:
        raise Exception(f"Not enough music channels on tick {tick_index + 1}")

      active_music[channel] = note if hold else None
      tick_channel_for_note[note] = channel

      emit_channel(out, MUSIC_OFFSET + channel)
      emit_freq(out, NOTE_FREQS[note])
      emit_on(out)

    elapsed = 0

    for phoneme in speech_tick:
      elapsed += emit_speech_phoneme(out, phoneme)

    remaining = MUSIC_ON_MS - elapsed

    if remaining < 0:
      out.append(f"; WARNING: speech overran tick by {-remaining}ms")
    else:
      emit_sleep(out, remaining)

    for note in instant_notes:
      channel = tick_channel_for_note[note]
      emit_channel(out, MUSIC_OFFSET + channel)
      emit_off(out)

    emit_sleep(out, BREAK_MS)
    out.append("")

  out.append("; end: stop all channels")
  emit_stop_range(out, 0, MUSIC_CHANNELS + SPEECH_CHANNELS)
  out.append("")

  return out


def main():
  with open("song.txt", "r") as f:
    song_lines = f.readlines()

  with open("speech.txt", "r") as f:
    speech_lines = f.readlines()

  out = compile_performance(song_lines, speech_lines)

  with open(OUTPUT_FILE, "w") as f:
    f.write("\n".join(out))

  print(f"Wrote {len(out)} lines to {OUTPUT_FILE}")

if __name__ == "__main__": main()
