import re
from imm import i as construct

CHANNEL_COUNT = 4
TOTAL_NOTE_LENGTH = 1000
BREAK_LENGTH = 30

OUTPUT_FILE = "song.craw"

NOTE_FREQS = {
  "A0": 28, "A#0": 29, "Bb0": 29, "B0": 31,

  "C1": 33, "C#1": 35, "Db1": 35, "D1": 37, "D#1": 39, "Eb1": 39,
  "E1": 41, "F1": 44, "F#1": 46, "Gb1": 46, "G1": 49, "G#1": 52,
  "Ab1": 52, "A1": 55, "A#1": 58, "Bb1": 58, "B1": 62,

  "C2": 65, "C#2": 69, "Db2": 69, "D2": 73, "D#2": 78, "Eb2": 78,
  "E2": 82, "F2": 87, "F#2": 93, "Gb2": 93, "G2": 98, "G#2": 104,
  "Ab2": 104, "A2": 110, "A#2": 117, "Bb2": 117, "B2": 123,

  "C3": 131, "C#3": 139, "Db3": 139, "D3": 147, "D#3": 156, "Eb3": 156,
  "E3": 165, "F3": 175, "F#3": 185, "Gb3": 185, "G3": 196, "G#3": 208,
  "Ab3": 208, "A3": 220, "A#3": 233, "Bb3": 233, "B3": 247,

  "C4": 262, "C#4": 277, "Db4": 277, "D4": 294, "D#4": 311, "Eb4": 311,
  "E4": 330, "F4": 349, "F#4": 370, "Gb4": 370, "G4": 392, "G#4": 415,
  "Ab4": 415, "A4": 440, "A#4": 466, "Bb4": 466, "B4": 494,

  "C5": 523, "C#5": 554, "Db5": 554, "D5": 587, "D#5": 622, "Eb5": 622,
  "E5": 659, "F5": 698, "F#5": 740, "Gb5": 740, "G5": 784, "G#5": 831,
  "Ab5": 831, "A5": 880, "A#5": 932, "Bb5": 932, "B5": 988,

  "C6": 1047, "C#6": 1109, "Db6": 1109, "D6": 1175, "D#6": 1245, "Eb6": 1245,
  "E6": 1319, "F6": 1397, "F#6": 1480, "Gb6": 1480, "G6": 1568,
  "G#6": 1661, "Ab6": 1661, "A6": 1760, "A#6": 1865, "Bb6": 1865,
  "B6": 1976,

  "C7": 2093, "C#7": 2217, "Db7": 2217, "D7": 2349, "D#7": 2489,
  "Eb7": 2489, "E7": 2637, "F7": 2794, "F#7": 2960, "Gb7": 2960,
  "G7": 3136, "G#7": 3322, "Ab7": 3322, "A7": 3520, "A#7": 3729,
  "Bb7": 3729, "B7": 3951,

  "C8": 4186,
}

NOTE_RE = re.compile(r"^[A-G](#|b)?[0-8]\*?$")

def insert_large(value, crawssembly):
  if -128 <= value <= 127:
    crawssembly.append(f"sav {value} r01")
    return crawssembly

  crawssembly.append("sav 7 r02")
  blocks = construct(value, 0, False)

  for i, block in enumerate(blocks):
    if i + 1 == len(blocks):
      crawssembly.append(f"cal add {block} r01")
    else:
      crawssembly.extend([
        f"sav {block} r01",
        "cal shl r01 r02",
      ])

  return crawssembly

def emit_select_channel(out, channel):
  out.extend([
    f"sav {channel} r01",
    "io speaker channel r01",
  ])


def emit_set_freq(out, note):
  out = insert_large(NOTE_FREQS[note], out)
  out.append("io speaker freq r01")
  return out

def emit_on(out): out.append("io speaker on rff")

def emit_off(out): out.append("io speaker off rff")

def emit_sleep(out, ms_reg): out.append(f"io time sleep {ms_reg}")

def parse_tick(raw_line, line_number):
  line = raw_line.split(";")[0].strip()

  if line == "" or line == "-": return []

  tokens = line.split()
  parsed = []

  for token in tokens:
    if not NOTE_RE.match(token):
      raise Exception(f"Bad note token '{token}' on line {line_number}")

    hold = token.endswith("*")
    note = token[:-1] if hold else token

    if note not in NOTE_FREQS:
      raise Exception(f"Unknown note '{note}' on line {line_number}")

    parsed.append((note, hold))

  notes_only = [note for note, _ in parsed]
  if len(notes_only) != len(set(notes_only)): raise Exception(f"Duplicate note on line {line_number}: {raw_line.strip()}")

  if len(parsed) > CHANNEL_COUNT:
    raise Exception(
      f"Too many notes on line {line_number}; "
      f"got {len(parsed)}, max is {CHANNEL_COUNT}"
    )

  return parsed

def free_channel(active):
  for channel in range(CHANNEL_COUNT):
    if active[channel] is None:
      return channel

  return None

def compile_song(lines):
  out = []

  out.extend([
    "; Generated by song_parser.py (C) CRAW SYSTEMS",
    "; Input: song.txt",
    "",
  ])

  insert_large(TOTAL_NOTE_LENGTH - BREAK_LENGTH, out)
  out.append("sav r01 r0a\t\t; enabled note length (ms)")

  insert_large(BREAK_LENGTH, out)
  out.append("sav r01 r0b\t\t; disabled break length (ms)")

  out.extend([
    "",
    "sav 100 r02\t\t; volume",
    "sav 0 r03\t\t; wave type",
    "",
  ])

  for channel in range(CHANNEL_COUNT):
    emit_select_channel(out, channel)
    out.extend([
      "io speaker volume r02",
      "io speaker wave r03",
      "io speaker off rff",
      "",
    ])

  active = {channel: None for channel in range(CHANNEL_COUNT)}

  for line_index, raw_line in enumerate(lines, start=1):
    tick = parse_tick(raw_line, line_index)
    tick_notes = {note for note, _ in tick}
    sustained_notes = {note for note, hold in tick if hold}
    instant_notes = {note for note, hold in tick if not hold}

    out.append(f"; tick {line_index}: {raw_line.strip()}")

    # Stop held notes that have disappeared.
    for channel, note in list(active.items()):
      if note is not None and note not in tick_notes:
        emit_select_channel(out, channel)
        emit_off(out)
        active[channel] = None

    # Keep existing sustained notes. If a held note appears again, do not retrigger it.
    already_active = {
      note: channel
      for channel, note in active.items()
      if note is not None
    }

    # Start new notes.
    tick_channel_for_note = {}

    for note, hold in tick:
      if note in already_active:
        tick_channel_for_note[note] = already_active[note]
        continue

      channel = free_channel(active)
      if channel is None:
        raise Exception(f"Not enough free channels on line {line_index}")

      active[channel] = note if hold else None
      tick_channel_for_note[note] = channel

      emit_select_channel(out, channel)
      emit_set_freq(out, note)
      emit_on(out)

    # Sleep while notes sound.
    emit_sleep(out, "r0a")

    # Stop instant notes only.
    for note in instant_notes:
      channel = tick_channel_for_note[note]
      emit_select_channel(out, channel)
      emit_off(out)

    # Held notes marked without * next tick will be stopped at the top of that next tick.
    emit_sleep(out, "r0b")
    out.append("")

  # Stop anything still holding at the end.
  out.append("; end: stop remaining held notes")
  for channel, note in active.items():
    if note is not None:
      emit_select_channel(out, channel)
      emit_off(out)

  out.append("")
  return out

def main():
  with open("song.txt", "r") as f: lines = f.readlines()

  crawssembly = compile_song(lines)

  with open(OUTPUT_FILE, "w") as f:
    f.write("\n".join(crawssembly))

  print(f"Wrote {len(crawssembly)} lines to {OUTPUT_FILE}")

if __name__ == "__main__": main()
